---
kind: pipeline
type: docker
name: packer

steps:
  - name: ubuntu-20.04-server-amd64
    image: hashicorp/packer:1.6.6
    network_mode: host
    environment:
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASSWORD:
        from_secret: proxmox_password
      TEMPLATE_VMID: 1000
    commands:
      - cd $DRONE_STEP_NAME
      - packer build -var-file=../drone.json packer.json
  - name: ubuntu-18.04.4-server-amd64
    image: hashicorp/packer:1.6.6
    network_mode: host
    environment:
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASSWORD:
        from_secret: proxmox_password
      TEMPLATE_VMID: 1001
    commands:
      - cd $DRONE_STEP_NAME
      - packer build -var-file=../drone.json packer.json
  - name: finish
    image: hashicorp/packer:1.6.6
    commands:
      - ls
    depends_on:
      - ubuntu-18.04.4-server-amd64
      - ubuntu-20.04-server-amd64
trigger:
  event:
  - push