---
packer-vm: &packer-vm
  image: hashicorp/packer:1.7.4
  depends_on:
    - delete
  network_mode: host
  environment:
    PROXMOX_USER:
      from_secret: proxmox_user
    PROXMOX_PASSWORD:
      from_secret: proxmox_password
  commands:
    - cd $DRONE_STEP_NAME
    - packer build -var-file=../drone.json packer.json

kind: pipeline
type: docker
name: packer-home
node:
  location: home
environment:
  PROXMOX_HOST: nuc.t-d.dev:443
  PROXMOX_NODE: nuc8i5beh
  PROXMOX_DATASTORE: local
  PROXMOX_DATASTORE_TYPE: directory
  PROXMOX_ISO_STORAGE: synology
steps:
  - name: delete
    image: ubuntu
    environment:
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASSWORD:
        from_secret: proxmox_password
    commands:
      - apt update && apt install unzip wget -y
      - wget https://github.com/Corsinvest/cv4pve-cli/releases/download/v1.6.5/cv4pve-cli-linux-x64.zip
      - unzip cv4pve-cli-linux-x64.zip -d /usr/local/bin
      - chmod 700 /usr/local/bin/cv4pve-cli
      - cv4pve-cli --host $PROXMOX_HOST --username $PROXMOX_USER@pve --password $PROXMOX_PASSWORD delete /nodes/$PROXMOX_NODE/qemu/1000 || true
      - cv4pve-cli --host $PROXMOX_HOST --username $PROXMOX_USER@pve --password $PROXMOX_PASSWORD delete /nodes/$PROXMOX_NODE/qemu/1001 || true
      - cv4pve-cli --host $PROXMOX_HOST --username $PROXMOX_USER@pve --password $PROXMOX_PASSWORD delete /nodes/$PROXMOX_NODE/qemu/1002 || true
      - cv4pve-cli --host $PROXMOX_HOST --username $PROXMOX_USER@pve --password $PROXMOX_PASSWORD delete /nodes/$PROXMOX_NODE/qemu/1005 || true
  - name: ubuntu-20.04-server-amd64
    <<: *packer-vm
    environment:
      TEMPLATE_VMID: 1000
  - name: ubuntu-18.04.4-server-amd64
    <<: *packer-vm
    environment:
      TEMPLATE_VMID: 1001
  - name: debian-10.9.0-amd64
    <<: *packer-vm
    environment:
      TEMPLATE_VMID: 1002
  - name: windows-server-2019
    <<: *packer-vm
    environment:
      TEMPLATE_VMID: 1005
    commands:
      - cd $DRONE_STEP_NAME
      - apk add cdrkit && mkisofs -J -l -R -V "Label CD" -iso-level 4 -o Autounattend.iso setup && export WIN_AUTOUNATTEND_ISO_CHECKSUM=$(sha256sum Autounattend.iso | awk '{print $1}') && echo $AUTOUNATTEND_CHECKSUM
      - packer build -var-file=../drone.json packer.json
trigger:
  event:
    - push

# ---
# packer-vm: &packer-vm
#   image: hashicorp/packer:1.7.4
#   depends_on:
#     - delete
#   network_mode: host
#   environment:
#     PROXMOX_USER:
#       from_secret: proxmox_user
#     PROXMOX_PASSWORD:
#       from_secret: proxmox_password
#   commands:
#     - cd $DRONE_STEP_NAME
#     - packer build -var-file=../drone.json packer.json

# kind: pipeline
# type: docker
# name: packer-hetzner
# node:
#   location: hetzner
# environment:
#   PROXMOX_HOST: t-dietrich.com
#   PROXMOX_NODE: proxmox
#   PROXMOX_DATASTORE: storage
#   PROXMOX_DATASTORE_TYPE: directory
#   PROXMOX_ISO_STORAGE: images
# steps:
#   - name: delete
#     image: ubuntu
#     environment:
#       PROXMOX_USER:
#         from_secret: proxmox_user
#       PROXMOX_PASSWORD:
#         from_secret: proxmox_password
#     commands:
#       - apt update && apt install unzip wget -y
#       - wget https://github.com/Corsinvest/cv4pve-cli/releases/download/v1.6.5/cv4pve-cli-linux-x64.zip
#       - unzip cv4pve-cli-linux-x64.zip -d /usr/local/bin
#       - chmod 700 /usr/local/bin/cv4pve-cli
#       - cv4pve-cli --host $PROXMOX_HOST --username $PROXMOX_USER@pve --password $PROXMOX_PASSWORD delete /nodes/$PROXMOX_NODE/qemu/1000 || true
#   - name: ubuntu-20.04-server-amd64
#     <<: *packer-vm
#     environment:
#       TEMPLATE_VMID: 1000
# trigger:
#   event:
#     - push