---
kind: pipeline
type: docker
name: packer

steps:
- name: ubuntu-20.04
  image: hashicorp/packer:1.6.6
  network_mode: host
  commands:
    - cd ubuntu-20.04-server-amd64
    - packer build -var-file=drone.json ubuntu-20.04.json
  environment:
    TF_PASSWORD:
      from_secret: terraform_password
trigger:
  event:
  - push