name: AlmaLinux-9
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['almalinux-9.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: almalinux-9
      vm_id: 1011
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
