name: Alpine-3.14
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: alpine-3.14
      vm_id: 1004
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
