name: Debian-10
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: debian-10
      vm_id: 1002
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
