name: Debian-12
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['debian-12.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: debian-12
      vm_id: 1006
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
