name: Ubuntu-18.04
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['ubuntu-18.04.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: ubuntu-18.04
      vm_id: 1001
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
      NETBIRD_SETUP_KEY: ${{ secrets.NETBIRD_SETUP_KEY }}
