name: Ubuntu-20.04
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['ubuntu-20.04.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: ubuntu-20.04
      vm_id: 1000
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
