name: Windows-Server-2019
on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: windows-server-2019
      vm_id: 1005
      os_type: windows
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
